import React from 'react';
import FairScoreDisplay from '../components/FairScoreDisplay';

const FairScoreTest = () => {
  // Test data that mimics what the Lambda function would create
  const testDatasetKey = 'user-uploads/raw/test-dataset-123456789';

  return (
    <div className="p-8 max-w-4xl mx-auto">
      <h1 className="text-2xl font-bold mb-6">FAIR Score Integration Test</h1>
      
      <div className="space-y-6">
        <div className="bg-white rounded-lg border p-6">
          <h2 className="text-lg font-semibold mb-4">Compact FAIR Score Display</h2>
          <FairScoreDisplay datasetKey={testDatasetKey} compact={true} />
        </div>
        
        <div className="bg-white rounded-lg border p-6">
          <h2 className="text-lg font-semibold mb-4">Full FAIR Score Display</h2>
          <FairScoreDisplay datasetKey={testDatasetKey} compact={false} />
        </div>
        
        <div className="bg-gray-50 rounded-lg p-6">
          <h2 className="text-lg font-semibold mb-4">Integration Notes</h2>
          <ul className="list-disc list-inside space-y-2 text-sm text-gray-700">
            <li>FAIR scores are automatically generated by the Lambda function when datasets are uploaded</li>
            <li>Scores are stored as <code className="bg-gray-200 px-1 rounded">fairscore.json</code> files in each dataset folder</li>
            <li>The component fetches scores dynamically and displays them with visual indicators</li>
            <li>If no score is available, it shows a "processing" or "not available" message</li>
            <li>FAIR scores appear in dataset lists, explore pages, and project views</li>
          </ul>
        </div>
      </div>
    </div>
  );
};

export default FairScoreTest;
